source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/xaoxuu/Specs.git'

platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

target 'InspireExample' do

  pod 'Inspire', :path => '..'
  pod 'AXKit', '0.3.10'
  
end
